version: "3.8"

services:
  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


  django:
    container_name: django
    build:
      context: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app

    ports:
      - "8000:8000"

    environment:
      - SECRET_KEY=testqwdpl[qwpld[pqlw[pdl[qpwld[pqwdl
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1

    depends_on:
      - redis
      - rabbitmq

  celery:
    container_name: celery-worker
    build:
      context: .
    volumes:
      - .:/app

    command: celery --app=RabitMQ worker -l INFO -Q tasks
    environment:
      - SECRET_KEY=testqwdpl[qwpld[pqlw[pdl[qpwld[pqwdl
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1

    depends_on:
      - redis
      - django
      - rabbitmq

#  flower:
#    image: mher/flower
#    ports:
#      - "5555:5555"
#    environment:
#      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/

#  stand_alone_celery:
#    container_name: stand_alone_celery
#    build:
#      context: ./worker/
#
#    volumes:
#      - ./worker/:/app
#
#    command: celery -A celery_base worker -l INFO -Q queue2
#    depends_on:
#      - redis
